name: Simulate External Ticket Lifecycle

on:
  workflow_dispatch:
    inputs:
      port_payload:
        required: true
        description: "Port event payload"
        type: string

jobs:
  simulate-ticket-lifecycle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Port Access Token
        id: generate-token
        run: |
          access_token=$(curl --location --request POST 'https://api.getport.io/v1/auth/access_token' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "clientId": "'"${{ secrets.PORT_CLIENT_ID }}"'",
              "clientSecret": "'"${{ secrets.PORT_CLIENT_SECRET }}"'"
          }' | jq -r '.accessToken')
          echo "ACCESS_TOKEN=$access_token" >> $GITHUB_ENV

      - name: Parse Ticket Payload
        id: parse-ticket
        run: |
          echo '${{ inputs.port_payload }}' > payload.json
          TYPE=$(jq -r '.diff.after.properties.type' payload.json)
          IDENTIFIER=$(jq -r '.diff.after.identifier' payload.json)
          echo "TYPE=$TYPE" >> $GITHUB_ENV
          echo "IDENTIFIER=$IDENTIFIER" >> $GITHUB_ENV

      - name: Create External Ticket Entity
        run: |
          if [[ "${TYPE}" == "Jira" ]]; then
            BLUEPRINT="jira_ticket"
            URL="https://jira.example.com/browse/${IDENTIFIER}"
            cat <<EOF > entity.json
{
  "identifier": "${IDENTIFIER}",
  "title": "Jira Ticket Simulation",
  "blueprint": "jira_ticket",
  "properties": {
    "jira_project": "PORT",
    "jira_issue_type": "Task",
    "jira_ticket_id": "${IDENTIFIER}",
    "jira_url": "${URL}",
    "status": "Open"
  },
  "relations": {
    "original_ticket": "${IDENTIFIER}"
  }
}
EOF

          elif [[ "${TYPE}" == "SharePoint" ]]; then
            BLUEPRINT="sharepoint_ticket"
            URL="https://sharepoint.example.com/tickets/${IDENTIFIER}"
            cat <<EOF > entity.json
{
  "identifier": "${IDENTIFIER}",
  "title": "SharePoint Ticket Simulation",
  "blueprint": "sharepoint_ticket",
  "properties": {
    "sharepoint_list": "IT Requests",
    "sharepoint_ticket_id": "${IDENTIFIER}",
    "sharepoint_url": "${URL}",
    "status": "Open"
  },
  "relations": {
    "original_ticket": "${IDENTIFIER}"
  }
}
EOF

          else
            BLUEPRINT="other_ticket_system"
            cat <<EOF > entity.json
{
  "identifier": "${IDENTIFIER}",
  "title": "Other Ticket Simulation",
  "blueprint": "other_ticket_system",
  "properties": {
    "ticket_id": "${IDENTIFIER}",
    "status": "Open"
  },
  "relations": {
    "original_ticket": "${IDENTIFIER}"
  }
}
EOF
          fi

          echo "BLUEPRINT=$BLUEPRINT" >> $GITHUB_ENV

          curl -s -X POST "https://api.getport.io/v1/blueprints/${BLUEPRINT}/entities" \
            -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d @entity.json

      - name: Simulate Status: In-Progress
        run: |
          sleep 30
          curl -s -X PATCH "https://api.getport.io/v1/blueprints/${{ env.BLUEPRINT }}/entities/${{ env.IDENTIFIER }}" \
            -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"properties": { "status": "In Progress" }}'

      - name: Simulate Status: Resolved
        run: |
          sleep 30
          curl -s -X PATCH "https://api.getport.io/v1/blueprints/${{ env.BLUEPRINT }}/entities/${{ env.IDENTIFIER }}" \
            -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"properties": { "status": "Resolved" }}'

      - name: Simulate Status: Closed
        run: |
          sleep 30
          curl -s -X PATCH "https://api.getport.io/v1/blueprints/${{ env.BLUEPRINT }}/entities/${{ env.IDENTIFIER }}" \
            -H "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"properties": { "status": "Closed" }}'
